name: static-analysis

on:
  workflow_call:
    inputs:
      go:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go }}

      - name: Install linters
        run: |
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.3
          go install github.com/client9/misspell/cmd/misspell@v0.3.4

      - name: Vetting
        run: go vet ./...

      - name: Run staticcheck
        if: always()
        run: ~/go/bin/staticcheck -checks all ./...

      - name: Run misspell
        if: always()
        run: ~/go/bin/misspell -error ./...

      - name: Run golint
        if: always()
        run: ~/go/bin/golint -set_exit_status ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go }}

      - name: Testing
        run: go test --race ./...

